### ISSUE TITLE
await expression is only allowed within an async function

### ISSUE THREAD

**Issue by rogerfar** [gradecam/jasmine-co#5]
I tried to follow the TS example from the readme but I'm confused how TS is supposed to know that `it` is an async function.

I call `require('jasmine-co').install();` but I still get error `await expression is only allowed within an async function` as the definition files still point to @types\jasmine\index.d.ts

Do I have to update the definition files from jasmine-co?

**Comment by putermancer** [comment]
`it` is not an async function, but the second argument you pass to `it` should be. 

```
it("is awesome", async function() {
    await something();
});
```

**Comment by rogerfar** [comment]
My apologies! I didn't see that part of the example, it works great now, thanks!
