### ISSUE TITLE
Tests marked as passed while they should fail

### ISSUE THREAD

**Issue by rogerfar** [gradecam/jasmine-co#6]
I recreated the example in typescript:

```
function getUser(userId: number): Promise<string> {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(`user${userId}`);
        }, 1000);
    })
}

function getBooksForUser(user: string): Promise<string[]> {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(['book1', 'book2']);
        }, 1000);
    })
}

// spec/bookService.spec.ts
describe("user models", function () {
    beforeEach(async function () {
        this.user = await this.getUser(1);
    });

    it("should be able to get a list of owned books", async function () {
        var books = await this.getBooksForUser(this.user);
        expect(books).toEqual('test');
    });
});
```

And when running the tests it takes a while for it to complete, but it always passes:
`Chrome 55.0.2883 (Windows 10 0.0.0): Executed 1 of 1 SUCCESS (6.419 secs / 0.005 secs)`

When moving the `expect` above the `var books...` statement, it will correctly fail.

**Comment by putermancer** [comment]
I'm not able to reproduce what you're stating. When I run the code exactly as given above, I encounter "TypeError: this.getUser is not a function" and "TypeError: this.getBooksForUser is not a function"—this makes sense, because they are just scope level functions, not part of `this`.

When I change `this.getUser` -> `getUser` and `this.getBooksForUser` -> `getBooksForUser`, I get "Error: Expected [ 'book1', 'book2' ] to equal 'test'" (as expected).

I suspect there is something off with your environment config; whether it's an issue with your tsconfig or your Jasmine config, I can't say.

**Comment by rogerfar** [comment]
Would you mind sharing your config so I can check?

**Comment by putermancer** [comment]
I tested it by creating a new spec file in the project I'm currently working on—it's not a simple environment with a standalone config. I will look into spending a few minutes making a very simple environment, though.

**Comment by putermancer** [comment]
Here's an extremely simple `.tsconfig` which is working fine for me. The only difference in this from what is output by `tsc --init` is that I changed the target to "es6".

I have also installed `@types/jasmine` and `@types/node` so TypeScript knows about `require`, `describe`, etc.

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "sourceMap": false
    }
}
```

Here's the spec file:

```typescript
const jasmineCo = require("../index"); // tslint:disable-line

function getUser(userId: number): Promise<string> {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(`user${userId}`);
        }, 1000);
    });
}

function getBooksForUser(user: string): Promise<string[]> {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(["book1", "book2"]);
        }, 1000);
    });
}

describe("test github issues", function () {
    jasmineCo.install();
    it("should be able to get a list of owned books", async function () {
        let books = await getBooksForUser(this.user);
        expect(books).toEqual("test");
    });
    jasmineCo.uninstall();
});
```

It works fine as long as I run `tsc` before running the specs: `tsc && jasmine`

Here's my very simple `support/jasmine.json` file as well:

```json
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ]
}
```

**Comment by rogerfar** [comment]
Ok I'm using karma-typescript, and it might throw things off, because with your code I get `Error: 'expect' was used when there was no current spec, this could be because an asynchronous test timed out`.

I'll try to get rid of it, and see if that helps.
